AllCops:
  Exclude:
    - 'spec/**/*'
    - 'vendor/**/*'
Metrics/AbcSize:
  Max: 30
Metrics/LineLength:
  Max: 150
Metrics/MethodLength:
  Max: 30
Style/Documentation:
  Enabled: false
Style/SignalException:
  Enabled: false
Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space
Layout/SpaceInsideBrackets:
  Enabled: false
