language: ruby
cache: bundler
sudo: false

rvm:
  - 2.3.4
  - 2.4.1
  - ruby-head

branches:
  only:
    - master

matrix:
  allow_failures:
    - rvm: ruby-head

script:
  - bundle exec rake style
  - bundle exec rake spec

notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: fu2EAP4pBts00ofX/5WWPevugan8gqhbTnR3peQ6AHD89JrCyBPfhk3LJk2Nk8OzChHLETIjm9n1CvnnFIXZw+dRidN/lY47WFHPAIWBWfooS9eHR9liKqfnFodn6sJR+eifbOPGd3SMEdPdUIN8M/8/XhHvP4iZ6CjHwvTpWBZ6XAJY8RGtTfIM5Eup1de5bdHpolazGoydRgrP0biQKTMvVG6McyS3VXbZgoXof7Y78uBpEeJKqwUDPCdvCDR3ulcz/AkitlmAaotkU4k/CTR+VSRhYYSqRMRvVU0QYP/wSgf6es8g0YzkAs1KJrhV//OH5Y7w2Fsrr8rOKrFoXmMvqzw8KEGmIUwMzMJwizud7Mz5scCuDaGt5btQjMZcHS/i5s7iU2bxb2dFfQYs18t8s2xAWaFs2bytNc8G5+vObjY5ZAa3uS1YINZCuMeiclmK3mGCcMUS5xqIy6+dURmqoyPNPJcODh6XdX4VAXvTorb7eOxDCO0fgWL3qO6eRpMIcnMm3/UZznroYiWWH2LZHV9GqYG4ePRUCQFWQzp92Fzsl9j1aAthG11JOJpSjKt+jlM3HZTm55IC+jkHW37+ULOkLuzKzvu24R0wdVjgyKr8SIhI5OGV2NQAl86JJeY1ptxOiJEAldrsfgpzFJ9ZriDahVxBAhRnqgo6jTo=
